export const stationList: string[] = [
    "Recto",
    "Legarda",
    "Pureza",
    "V. Mapa",
    "J. Ruiz",
    "Gilmore",
    "Betty Go",
    "Cubao",
    "Anonas",
    "Katipunan",
    "Santolan",
    "Marikina",
    "Antipolo",
  ];